-- Seed 100 realistic skincare and makeup products

-- SKINCARE PRODUCTS (50 products)

-- Cleansers (8 products)
INSERT INTO products (name, slug, category, subcategory, description, ingredients, benefits, skin_type, price, stock, image_url) VALUES
('Gentle Foaming Cleanser', 'gentle-foaming-cleanser', 'skincare', 'Cleanser', 'A mild, pH-balanced foaming cleanser that removes impurities without stripping natural oils', 'Water, Glycerin, Sodium Cocoyl Isethionate, Cocamidopropyl Betaine, Niacinamide', 'Removes makeup and impurities, Maintains skin pH balance, Hydrates while cleansing', ARRAY['normal', 'combination', 'sensitive'], 24.99, 150, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Hydrating Gel Cleanser', 'hydrating-gel-cleanser', 'skincare', 'Cleanser', 'Refreshing gel cleanser with hyaluronic acid for deep hydration', 'Hyaluronic Acid, Aloe Vera, Cucumber Extract, Vitamin E', 'Deep cleansing, Intense hydration, Soothes irritation', ARRAY['dry', 'sensitive'], 28.50, 120, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Charcoal Detox Cleanser', 'charcoal-detox-cleanser', 'skincare', 'Cleanser', 'Activated charcoal cleanser that draws out impurities and toxins', 'Activated Charcoal, Tea Tree Oil, Salicylic Acid, Kaolin Clay', 'Detoxifies pores, Controls oil, Prevents breakouts', ARRAY['oily', 'combination', 'acne-prone'], 26.00, 100, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Micellar Water Cleanser', 'micellar-water-cleanser', 'skincare', 'Cleanser', 'No-rinse micellar water that gently removes makeup and cleanses', 'Micellar Technology, Rose Water, Glycerin', 'Removes makeup effortlessly, No rinsing required, Gentle on skin', ARRAY['all'], 22.00, 200, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Oil-Balancing Cleanser', 'oil-balancing-cleanser', 'skincare', 'Cleanser', 'Balancing cleanser with niacinamide for oil control', 'Niacinamide, Zinc PCA, Green Tea Extract', 'Balances sebum production, Minimizes pores, Mattifies skin', ARRAY['oily', 'combination'], 27.50, 110, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Cream Cleanser', 'cream-cleanser', 'skincare', 'Cleanser', 'Rich, creamy cleanser for dry and mature skin', 'Shea Butter, Ceramides, Peptides, Vitamin E', 'Nourishes dry skin, Maintains moisture barrier, Anti-aging benefits', ARRAY['dry', 'mature'], 32.00, 90, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Exfoliating Cleanser', 'exfoliating-cleanser', 'skincare', 'Cleanser', 'Daily exfoliating cleanser with gentle microbeads', 'Jojoba Beads, Lactic Acid, Vitamin C', 'Gentle exfoliation, Brightens complexion, Smooths texture', ARRAY['normal', 'combination'], 29.99, 85, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Sensitive Skin Cleanser', 'sensitive-skin-cleanser', 'skincare', 'Cleanser', 'Ultra-gentle cleanser for reactive and sensitive skin', 'Colloidal Oatmeal, Chamomile, Allantoin', 'Calms redness, Reduces irritation, Fragrance-free', ARRAY['sensitive'], 30.00, 75, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),

-- Serums (12 products)
('Vitamin C Brightening Serum', 'vitamin-c-brightening-serum', 'skincare', 'Serum', 'Potent 20% vitamin C serum for radiant, even-toned skin', 'L-Ascorbic Acid 20%, Ferulic Acid, Vitamin E, Hyaluronic Acid', 'Brightens dark spots, Evens skin tone, Boosts collagen', ARRAY['all'], 45.00, 200, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Hyaluronic Acid Serum', 'hyaluronic-acid-serum', 'skincare', 'Serum', 'Multi-molecular weight hyaluronic acid for deep hydration', 'Hyaluronic Acid (3 molecular weights), Vitamin B5, Glycerin', 'Intense hydration, Plumps fine lines, Locks in moisture', ARRAY['dry', 'normal', 'mature'], 38.00, 180, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Retinol Night Serum', 'retinol-night-serum', 'skincare', 'Serum', 'Advanced retinol serum for anti-aging and skin renewal', 'Retinol 0.5%, Peptides, Squalane, Niacinamide', 'Reduces wrinkles, Improves texture, Stimulates cell turnover', ARRAY['normal', 'mature', 'combination'], 52.00, 150, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Niacinamide Serum', 'niacinamide-serum', 'skincare', 'Serum', '10% niacinamide serum for pore refinement and oil control', 'Niacinamide 10%, Zinc PCA, Tamarind Extract', 'Minimizes pores, Controls oil, Evens skin tone', ARRAY['oily', 'combination', 'acne-prone'], 35.00, 220, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Peptide Complex Serum', 'peptide-complex-serum', 'skincare', 'Serum', 'Multi-peptide serum for firming and anti-aging', 'Matrixyl 3000, Argireline, Copper Peptides, Hyaluronic Acid', 'Firms skin, Reduces wrinkles, Boosts elasticity', ARRAY['mature', 'normal'], 58.00, 100, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Azelaic Acid Serum', 'azelaic-acid-serum', 'skincare', 'Serum', '10% azelaic acid for acne and hyperpigmentation', 'Azelaic Acid 10%, Niacinamide, Salicylic Acid', 'Treats acne, Fades dark spots, Evens texture', ARRAY['acne-prone', 'oily', 'combination'], 42.00, 130, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Vitamin E Antioxidant Serum', 'vitamin-e-antioxidant-serum', 'skincare', 'Serum', 'Protective antioxidant serum with vitamin E', 'Vitamin E, Ferulic Acid, Green Tea Extract, Resveratrol', 'Protects from free radicals, Anti-aging, Nourishes skin', ARRAY['all'], 40.00, 160, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Glycolic Acid Serum', 'glycolic-acid-serum', 'skincare', 'Serum', '7% glycolic acid exfoliating serum', 'Glycolic Acid 7%, Aloe Vera, Hyaluronic Acid', 'Exfoliates dead skin, Brightens complexion, Smooths texture', ARRAY['normal', 'combination'], 36.00, 140, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Tranexamic Acid Serum', 'tranexamic-acid-serum', 'skincare', 'Serum', 'Tranexamic acid serum for dark spots and melasma', 'Tranexamic Acid 5%, Kojic Acid, Niacinamide', 'Fades melasma, Reduces dark spots, Brightens skin', ARRAY['all'], 48.00, 110, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Bakuchiol Serum', 'bakuchiol-serum', 'skincare', 'Serum', 'Natural retinol alternative for sensitive skin', 'Bakuchiol, Squalane, Vitamin E, Peptides', 'Anti-aging without irritation, Improves elasticity, Gentle on skin', ARRAY['sensitive', 'mature'], 50.00, 95, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Centella Calming Serum', 'centella-calming-serum', 'skincare', 'Serum', 'Soothing centella asiatica serum for irritated skin', 'Centella Asiatica 80%, Madecassoside, Panthenol', 'Calms irritation, Repairs skin barrier, Reduces redness', ARRAY['sensitive', 'acne-prone'], 39.00, 170, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Alpha Arbutin Serum', 'alpha-arbutin-serum', 'skincare', 'Serum', 'Brightening serum with alpha arbutin', 'Alpha Arbutin 2%, Vitamin C, Licorice Extract', 'Brightens skin, Fades hyperpigmentation, Even tone', ARRAY['all'], 37.00, 155, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),

-- Moisturizers (10 products)
('Lightweight Gel Moisturizer', 'lightweight-gel-moisturizer', 'skincare', 'Moisturizer', 'Oil-free gel moisturizer for oily and combination skin', 'Hyaluronic Acid, Niacinamide, Green Tea Extract', 'Hydrates without grease, Mattifies skin, Controls oil', ARRAY['oily', 'combination'], 32.00, 180, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Rich Cream Moisturizer', 'rich-cream-moisturizer', 'skincare', 'Moisturizer', 'Deeply nourishing cream for dry and mature skin', 'Shea Butter, Ceramides, Peptides, Squalane', 'Intense hydration, Repairs barrier, Anti-aging', ARRAY['dry', 'mature'], 44.00, 140, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Barrier Repair Moisturizer', 'barrier-repair-moisturizer', 'skincare', 'Moisturizer', 'Ceramide-rich moisturizer for damaged skin barriers', 'Ceramides 1,3,6, Cholesterol, Fatty Acids, Niacinamide', 'Repairs skin barrier, Locks in moisture, Strengthens skin', ARRAY['dry', 'sensitive'], 48.00, 120, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Overnight Recovery Cream', 'overnight-recovery-cream', 'skincare', 'Moisturizer', 'Intensive overnight cream for skin renewal', 'Retinol, Peptides, Hyaluronic Acid, Vitamin E', 'Repairs overnight, Reduces wrinkles, Boosts radiance', ARRAY['mature', 'normal'], 55.00, 100, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Soothing Cica Cream', 'soothing-cica-cream', 'skincare', 'Moisturizer', 'Calming moisturizer with centella for sensitive skin', 'Centella Asiatica, Madecassoside, Panthenol, Allantoin', 'Calms redness, Soothes irritation, Fragrance-free', ARRAY['sensitive'], 38.00, 160, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Oil-Control Moisturizer', 'oil-control-moisturizer', 'skincare', 'Moisturizer', 'Mattifying moisturizer with sebum control', 'Niacinamide, Zinc PCA, Silica, Green Tea', 'Controls shine, Minimizes pores, Lightweight', ARRAY['oily', 'acne-prone'], 34.00, 190, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Brightening Moisturizer', 'brightening-moisturizer', 'skincare', 'Moisturizer', 'Illuminating moisturizer with vitamin C and niacinamide', 'Vitamin C, Niacinamide, Licorice Extract, Hyaluronic Acid', 'Brightens complexion, Evens tone, Hydrates', ARRAY['normal', 'combination'], 42.00, 150, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Hyaluronic Moisturizer', 'hyaluronic-moisturizer', 'skincare', 'Moisturizer', 'Plumping moisturizer with multi-weight hyaluronic acid', 'Hyaluronic Acid, Glycerin, Vitamin B5, Ceramides', 'Plumps skin, Deep hydration, Smooths fine lines', ARRAY['dry', 'normal'], 40.00, 170, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Anti-Aging Moisturizer', 'anti-aging-moisturizer', 'skincare', 'Moisturizer', 'Advanced anti-aging cream with retinol and peptides', 'Retinol, Matrixyl, Hyaluronic Acid, Vitamin E', 'Reduces wrinkles, Firms skin, Improves elasticity', ARRAY['mature'], 58.00, 90, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Probiotic Moisturizer', 'probiotic-moisturizer', 'skincare', 'Moisturizer', 'Balancing moisturizer with probiotics for skin microbiome', 'Probiotics, Prebiotics, Niacinamide, Ceramides', 'Balances microbiome, Strengthens barrier, Calms skin', ARRAY['sensitive', 'combination'], 46.00, 130, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),

-- Sunscreens (6 products)
('Mineral Sunscreen SPF 50', 'mineral-sunscreen-spf50', 'skincare', 'Sunscreen', 'Broad-spectrum mineral sunscreen with zinc oxide', 'Zinc Oxide 20%, Titanium Dioxide 5%, Vitamin E', 'UVA/UVB protection, Reef-safe, No white cast', ARRAY['all'], 35.00, 250, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Lightweight Chemical Sunscreen SPF 50', 'lightweight-chemical-sunscreen-spf50', 'skincare', 'Sunscreen', 'Invisible, fast-absorbing chemical sunscreen', 'Avobenzone, Octinoxate, Hyaluronic Acid, Niacinamide', 'No white cast, Hydrating, Lightweight', ARRAY['all'], 32.00, 280, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Tinted Sunscreen SPF 45', 'tinted-sunscreen-spf45', 'skincare', 'Sunscreen', 'Tinted mineral sunscreen with skin-perfecting coverage', 'Zinc Oxide, Iron Oxides, Vitamin C, Niacinamide', 'Evens skin tone, Sun protection, Natural finish', ARRAY['all'], 38.00, 200, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Hydrating Sunscreen SPF 50', 'hydrating-sunscreen-spf50', 'skincare', 'Sunscreen', 'Moisturizing sunscreen for dry skin', 'Avobenzone, Hyaluronic Acid, Ceramides, Vitamin E', 'Hydrates and protects, Plumps skin, Non-greasy', ARRAY['dry', 'normal'], 36.00, 220, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Matte Sunscreen SPF 50', 'matte-sunscreen-spf50', 'skincare', 'Sunscreen', 'Oil-control sunscreen with matte finish', 'Octinoxate, Niacinamide, Silica, Green Tea', 'Controls oil, Matte finish, Minimizes pores', ARRAY['oily', 'combination'], 34.00, 240, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Sensitive Skin Sunscreen SPF 50', 'sensitive-skin-sunscreen-spf50', 'skincare', 'Sunscreen', 'Fragrance-free mineral sunscreen for sensitive skin', 'Zinc Oxide, Titanium Dioxide, Allantoin, Bisabolol', 'Gentle formula, Calms skin, Fragrance-free', ARRAY['sensitive'], 37.00, 190, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),

-- Exfoliators (6 products)
('AHA/BHA Exfoliating Toner', 'aha-bha-exfoliating-toner', 'skincare', 'Exfoliator', 'Dual-action chemical exfoliant with glycolic and salicylic acid', 'Glycolic Acid 7%, Salicylic Acid 2%, Witch Hazel', 'Exfoliates surface and pores, Brightens, Unclogs pores', ARRAY['normal', 'oily', 'combination'], 30.00, 180, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Gentle Lactic Acid Exfoliant', 'gentle-lactic-acid-exfoliant', 'skincare', 'Exfoliator', 'Mild lactic acid exfoliant for sensitive skin', 'Lactic Acid 5%, Hyaluronic Acid, Aloe Vera', 'Gentle exfoliation, Hydrates, Brightens', ARRAY['sensitive', 'dry'], 28.00, 150, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Enzyme Exfoliating Mask', 'enzyme-exfoliating-mask', 'skincare', 'Exfoliator', 'Natural enzyme mask with papaya and pineapple', 'Papain, Bromelain, Vitamin C, Kaolin Clay', 'Dissolves dead skin, Brightens, Natural exfoliation', ARRAY['all'], 34.00, 120, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Physical Exfoliating Scrub', 'physical-exfoliating-scrub', 'skincare', 'Exfoliator', 'Gentle scrub with jojoba beads', 'Jojoba Beads, Vitamin E, Aloe Vera, Glycerin', 'Buffs away dead skin, Smooths texture, Non-abrasive', ARRAY['normal', 'combination'], 26.00, 160, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('PHA Exfoliating Serum', 'pha-exfoliating-serum', 'skincare', 'Exfoliator', 'Polyhydroxy acid serum for gentle exfoliation', 'Gluconolactone, Lactobionic Acid, Hyaluronic Acid', 'Gentle on sensitive skin, Hydrating, Anti-aging', ARRAY['sensitive', 'mature'], 38.00, 110, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Retinol Exfoliating Treatment', 'retinol-exfoliating-treatment', 'skincare', 'Exfoliator', 'Overnight retinol treatment for cell turnover', 'Retinol 0.3%, Niacinamide, Hyaluronic Acid', 'Accelerates cell turnover, Anti-aging, Smooths texture', ARRAY['normal', 'mature'], 42.00, 100, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),

-- Facewash (8 products)
('Foaming Facewash', 'foaming-facewash', 'skincare', 'Facewash', 'Deep cleansing foaming facewash for daily use', 'Sodium Laureth Sulfate, Glycerin, Aloe Vera, Vitamin E', 'Deep cleansing, Removes excess oil, Refreshes skin', ARRAY['oily', 'combination'], 18.00, 200, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Acne-Fighting Facewash', 'acne-fighting-facewash', 'skincare', 'Facewash', 'Salicylic acid facewash for acne-prone skin', 'Salicylic Acid 2%, Tea Tree Oil, Niacinamide', 'Treats acne, Unclogs pores, Prevents breakouts', ARRAY['acne-prone', 'oily'], 22.00, 180, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Hydrating Facewash', 'hydrating-facewash', 'skincare', 'Facewash', 'Creamy facewash that cleanses without drying', 'Glycerin, Hyaluronic Acid, Ceramides, Aloe Vera', 'Gentle cleansing, Maintains moisture, Soft skin', ARRAY['dry', 'sensitive'], 20.00, 170, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Brightening Facewash', 'brightening-facewash', 'skincare', 'Facewash', 'Vitamin C facewash for radiant skin', 'Vitamin C, Kojic Acid, Licorice Extract', 'Brightens complexion, Evens tone, Refreshing', ARRAY['normal', 'combination'], 24.00, 150, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'),
('Anti-Aging Facewash', 'anti-aging-facewash', 'skincare', 'Facewash', 'Peptide-infused facewash for mature skin', 'Peptides, Retinol, Hyaluronic Acid, Vitamin E', 'Anti-aging cleansing, Firms skin, Gentle formula', ARRAY['mature'], 28.00, 120, 'https://images.unsplash.com/photo-1556228720-195a672e8a03'),
('Charcoal Facewash', 'charcoal-facewash', 'skincare', 'Facewash', 'Detoxifying charcoal facewash', 'Activated Charcoal, Kaolin Clay, Tea Tree Oil', 'Detoxifies pores, Removes impurities, Deep cleansing', ARRAY['oily', 'combination'], 21.00, 190, 'https://images.unsplash.com/photo-1571875257727-256c39da42af'),
('Sensitive Skin Facewash', 'sensitive-skin-facewash', 'skincare', 'Facewash', 'Ultra-gentle facewash for reactive skin', 'Colloidal Oatmeal, Chamomile, Allantoin, Glycerin', 'Calms irritation, Fragrance-free, Hypoallergenic', ARRAY['sensitive'], 23.00, 140, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be'),
('Oil-Control Facewash', 'oil-control-facewash', 'skincare', 'Facewash', 'Mattifying facewash for oily skin', 'Niacinamide, Zinc PCA, Salicylic Acid, Green Tea', 'Controls oil, Mattifies, Prevents shine', ARRAY['oily'], 19.00, 210, 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b');

-- MAKEUP PRODUCTS (50 products)

-- Foundations (10 products)
INSERT INTO products (name, slug, category, subcategory, description, ingredients, benefits, skin_type, price, stock, image_url) VALUES
('Flawless Matte Foundation', 'flawless-matte-foundation', 'makeup', 'Foundation', 'Long-wear matte foundation with buildable coverage', 'Dimethicone, Titanium Dioxide, Iron Oxides, Vitamin E', 'Full coverage, Matte finish, 24-hour wear', ARRAY['oily', 'combination'], 42.00, 150, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Dewy Glow Foundation', 'dewy-glow-foundation', 'makeup', 'Foundation', 'Luminous foundation for radiant, glowing skin', 'Hyaluronic Acid, Glycerin, Mica, Vitamin C', 'Natural glow, Hydrating, Medium coverage', ARRAY['dry', 'normal'], 45.00, 140, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('HD Liquid Foundation', 'hd-liquid-foundation', 'makeup', 'Foundation', 'High-definition liquid foundation for flawless finish', 'Silica, Dimethicone, Niacinamide, Vitamin E', 'HD finish, Buildable, Long-lasting', ARRAY['all'], 48.00, 160, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Skin Tint Foundation', 'skin-tint-foundation', 'makeup', 'Foundation', 'Lightweight tinted moisturizer with SPF 30', 'Zinc Oxide, Hyaluronic Acid, Vitamin E, Iron Oxides', 'Sheer coverage, Sun protection, Natural finish', ARRAY['all'], 35.00, 180, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Full Coverage Foundation', 'full-coverage-foundation', 'makeup', 'Foundation', 'Maximum coverage foundation for flawless skin', 'Dimethicone, Titanium Dioxide, Kaolin, Vitamin E', 'Full coverage, Covers imperfections, Long-wear', ARRAY['all'], 50.00, 130, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Serum Foundation', 'serum-foundation', 'makeup', 'Foundation', 'Skincare-infused foundation with hyaluronic acid', 'Hyaluronic Acid, Niacinamide, Vitamin C, Peptides', 'Skincare benefits, Hydrating, Medium coverage', ARRAY['dry', 'normal'], 52.00, 120, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Oil-Free Foundation', 'oil-free-foundation', 'makeup', 'Foundation', 'Mattifying oil-free foundation for oily skin', 'Silica, Niacinamide, Zinc PCA, Iron Oxides', 'Controls oil, Matte finish, Pore-minimizing', ARRAY['oily', 'acne-prone'], 44.00, 155, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Cushion Foundation', 'cushion-foundation', 'makeup', 'Foundation', 'Portable cushion foundation with SPF 50', 'Zinc Oxide, Hyaluronic Acid, Niacinamide, Adenosine', 'Convenient application, Sun protection, Dewy finish', ARRAY['all'], 38.00, 170, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Stick Foundation', 'stick-foundation', 'makeup', 'Foundation', 'Creamy stick foundation for easy application', 'Shea Butter, Vitamin E, Jojoba Oil, Iron Oxides', 'Portable, Buildable, Creamy texture', ARRAY['dry', 'normal'], 40.00, 145, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Airbrush Foundation', 'airbrush-foundation', 'makeup', 'Foundation', 'Spray foundation for airbrushed finish', 'Dimethicone, Silica, Vitamin E, Iron Oxides', 'Flawless finish, Even application, Long-lasting', ARRAY['all'], 55.00, 100, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),

-- Concealers (8 products)
('Full Coverage Concealer', 'full-coverage-concealer', 'makeup', 'Concealer', 'High-coverage concealer for dark circles and blemishes', 'Dimethicone, Titanium Dioxide, Vitamin E, Caffeine', 'Covers dark circles, Hides blemishes, Crease-proof', ARRAY['all'], 28.00, 200, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Brightening Concealer', 'brightening-concealer', 'makeup', 'Concealer', 'Illuminating concealer with light-reflecting particles', 'Mica, Vitamin C, Hyaluronic Acid, Peptides', 'Brightens under-eyes, Hydrating, Radiant finish', ARRAY['all'], 30.00, 180, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Color Correcting Concealer', 'color-correcting-concealer', 'makeup', 'Concealer', 'Multi-shade concealer palette for color correction', 'Titanium Dioxide, Iron Oxides, Vitamin E', 'Corrects discoloration, Versatile, Professional', ARRAY['all'], 32.00, 150, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Liquid Concealer', 'liquid-concealer', 'makeup', 'Concealer', 'Lightweight liquid concealer with buildable coverage', 'Hyaluronic Acid, Niacinamide, Vitamin E, Iron Oxides', 'Natural finish, Buildable, Hydrating', ARRAY['all'], 26.00, 190, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Stick Concealer', 'stick-concealer', 'makeup', 'Concealer', 'Portable stick concealer for on-the-go touch-ups', 'Shea Butter, Vitamin E, Titanium Dioxide', 'Convenient, Full coverage, Creamy', ARRAY['all'], 24.00, 170, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Under-Eye Concealer', 'under-eye-concealer', 'makeup', 'Concealer', 'Specialized concealer for delicate under-eye area', 'Caffeine, Peptides, Hyaluronic Acid, Vitamin K', 'Reduces puffiness, Brightens, Hydrating', ARRAY['all'], 29.00, 160, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Acne Concealer', 'acne-concealer', 'makeup', 'Concealer', 'Medicated concealer with salicylic acid', 'Salicylic Acid, Tea Tree Oil, Sulfur, Iron Oxides', 'Treats while concealing, Anti-acne, Full coverage', ARRAY['acne-prone', 'oily'], 27.00, 140, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Waterproof Concealer', 'waterproof-concealer', 'makeup', 'Concealer', 'Long-wear waterproof concealer', 'Dimethicone, Titanium Dioxide, Vitamin E', 'Waterproof, Sweat-proof, 24-hour wear', ARRAY['all'], 31.00, 155, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),

-- Lipsticks (12 products)
('Matte Liquid Lipstick', 'matte-liquid-lipstick', 'makeup', 'Lipstick', 'Long-wear liquid lipstick with matte finish', 'Dimethicone, Vitamin E, Jojoba Oil, Iron Oxides', 'Matte finish, Transfer-proof, Long-lasting', ARRAY['all'], 22.00, 220, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa'),
('Satin Lipstick', 'satin-lipstick', 'makeup', 'Lipstick', 'Creamy satin lipstick with rich color', 'Shea Butter, Vitamin E, Castor Oil, Mica', 'Satin finish, Hydrating, Vibrant color', ARRAY['all'], 20.00, 240, 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92'),
('Glossy Lipstick', 'glossy-lipstick', 'makeup', 'Lipstick', 'High-shine glossy lipstick', 'Hyaluronic Acid, Vitamin E, Jojoba Oil, Mica', 'Glossy finish, Plumping, Hydrating', ARRAY['all'], 21.00, 200, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa'),
('Nude Lipstick', 'nude-lipstick', 'makeup', 'Lipstick', 'Perfect nude lipstick for everyday wear', 'Shea Butter, Vitamin E, Argan Oil, Iron Oxides', 'Natural nude, Comfortable, Versatile', ARRAY['all'], 19.00, 260, 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92'),
('Red Lipstick Classic', 'red-lipstick-classic', 'makeup', 'Lipstick', 'Iconic red lipstick with creamy formula', 'Shea Butter, Vitamin E, Castor Oil, Red 7 Lake', 'Classic red, Creamy, Long-wearing', ARRAY['all'], 23.00, 210, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa'),
('Plumping Lipstick', 'plumping-lipstick', 'makeup', 'Lipstick', 'Lip-plumping lipstick with hyaluronic acid', 'Hyaluronic Acid, Peptides, Vitamin E, Menthol', 'Plumps lips, Hydrating, Tingling sensation', ARRAY['all'], 25.00, 180, 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92'),
('Velvet Matte Lipstick', 'velvet-matte-lipstick', 'makeup', 'Lipstick', 'Soft matte lipstick with velvety texture', 'Dimethicone, Shea Butter, Vitamin E, Iron Oxides', 'Velvet finish, Comfortable, Non-drying', ARRAY['all'], 22.00, 195, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa'),
('Sheer Lipstick', 'sheer-lipstick', 'makeup', 'Lipstick', 'Lightweight sheer lipstick with hint of color', 'Jojoba Oil, Vitamin E, Shea Butter, Mica', 'Sheer coverage, Natural look, Hydrating', ARRAY['all'], 18.00, 230, 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92'),
('Metallic Lipstick', 'metallic-lipstick', 'makeup', 'Lipstick', 'Shimmering metallic lipstick', 'Mica, Titanium Dioxide, Vitamin E, Jojoba Oil', 'Metallic finish, Eye-catching, Unique', ARRAY['all'], 24.00, 170, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa'),
('Long-Wear Lipstick', 'long-wear-lipstick', 'makeup', 'Lipstick', '16-hour wear lipstick', 'Dimethicone, Vitamin E, Polymers, Iron Oxides', '16-hour wear, Transfer-resistant, Comfortable', ARRAY['all'], 26.00, 160, 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92'),
('Tinted Lip Balm', 'tinted-lip-balm', 'makeup', 'Lipstick', 'Nourishing tinted lip balm with SPF 15', 'Shea Butter, Beeswax, Vitamin E, Zinc Oxide', 'Hydrating, Sun protection, Sheer tint', ARRAY['all'], 15.00, 280, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa'),
('Berry Lipstick', 'berry-lipstick', 'makeup', 'Lipstick', 'Rich berry-toned lipstick', 'Shea Butter, Vitamin E, Castor Oil, Red 28 Lake', 'Berry shade, Creamy, Moisturizing', ARRAY['all'], 21.00, 205, 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92'),

-- Blush (6 products)
('Powder Blush', 'powder-blush', 'makeup', 'Blush', 'Silky powder blush with buildable color', 'Mica, Titanium Dioxide, Iron Oxides, Vitamin E', 'Buildable color, Blendable, Long-lasting', ARRAY['all'], 24.00, 180, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Cream Blush', 'cream-blush', 'makeup', 'Blush', 'Dewy cream blush for natural flush', 'Shea Butter, Jojoba Oil, Vitamin E, Iron Oxides', 'Dewy finish, Blendable, Natural glow', ARRAY['dry', 'normal'], 26.00, 160, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Liquid Blush', 'liquid-blush', 'makeup', 'Blush', 'Lightweight liquid blush with radiant finish', 'Glycerin, Hyaluronic Acid, Vitamin E, Mica', 'Radiant finish, Easy to blend, Long-wear', ARRAY['all'], 25.00, 170, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Matte Blush', 'matte-blush', 'makeup', 'Blush', 'Velvety matte powder blush', 'Silica, Mica, Iron Oxides, Vitamin E', 'Matte finish, Highly pigmented, Blendable', ARRAY['oily', 'combination'], 23.00, 190, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Shimmer Blush', 'shimmer-blush', 'makeup', 'Blush', 'Illuminating blush with subtle shimmer', 'Mica, Titanium Dioxide, Iron Oxides, Vitamin E', 'Subtle shimmer, Glowing, Buildable', ARRAY['all'], 27.00, 150, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Stick Blush', 'stick-blush', 'makeup', 'Blush', 'Portable stick blush for easy application', 'Shea Butter, Vitamin E, Jojoba Oil, Iron Oxides', 'Convenient, Creamy, Multi-use', ARRAY['all'], 22.00, 165, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),

-- Primers (4 products)
('Pore-Minimizing Primer', 'pore-minimizing-primer', 'makeup', 'Primer', 'Silicone-based primer that blurs pores', 'Dimethicone, Silica, Niacinamide, Vitamin E', 'Minimizes pores, Smooths texture, Extends wear', ARRAY['oily', 'combination'], 32.00, 140, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Hydrating Primer', 'hydrating-primer', 'makeup', 'Primer', 'Moisturizing primer for dry skin', 'Hyaluronic Acid, Glycerin, Vitamin E, Aloe Vera', 'Hydrates, Plumps, Dewy finish', ARRAY['dry', 'normal'], 30.00, 155, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Illuminating Primer', 'illuminating-primer', 'makeup', 'Primer', 'Radiance-boosting primer with light-reflecting particles', 'Mica, Vitamin C, Hyaluronic Acid, Glycerin', 'Adds glow, Brightens, Luminous finish', ARRAY['all'], 34.00, 130, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Mattifying Primer', 'mattifying-primer', 'makeup', 'Primer', 'Oil-control primer for shine-free makeup', 'Silica, Niacinamide, Zinc PCA, Dimethicone', 'Controls oil, Matte finish, Long-lasting', ARRAY['oily', 'acne-prone'], 31.00, 145, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),

-- Setting Spray (4 products)
('Matte Setting Spray', 'matte-setting-spray', 'makeup', 'Setting Spray', 'Long-wear setting spray with matte finish', 'Alcohol, Niacinamide, Green Tea Extract, Aloe Vera', 'Sets makeup, Matte finish, 16-hour wear', ARRAY['oily', 'combination'], 28.00, 170, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Dewy Setting Spray', 'dewy-setting-spray', 'makeup', 'Setting Spray', 'Hydrating setting spray for radiant finish', 'Glycerin, Hyaluronic Acid, Rose Water, Aloe Vera', 'Sets makeup, Dewy glow, Hydrating', ARRAY['dry', 'normal'], 29.00, 160, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Illuminating Setting Spray', 'illuminating-setting-spray', 'makeup', 'Setting Spray', 'Glow-enhancing setting spray with shimmer', 'Mica, Glycerin, Rose Water, Vitamin E', 'Adds radiance, Sets makeup, Luminous', ARRAY['all'], 30.00, 150, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Long-Lasting Setting Spray', 'long-lasting-setting-spray', 'makeup', 'Setting Spray', 'Maximum hold setting spray for all-day wear', 'Alcohol, Polymers, Aloe Vera, Vitamin E', '24-hour hold, Waterproof, Transfer-proof', ARRAY['all'], 32.00, 140, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),

-- Compact/Powder (6 products)
('Translucent Setting Powder', 'translucent-setting-powder', 'makeup', 'Compact / Powder', 'Invisible setting powder for all skin tones', 'Silica, Mica, Vitamin E', 'Sets makeup, No flashback, Blurs imperfections', ARRAY['all'], 35.00, 180, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Pressed Powder Compact', 'pressed-powder-compact', 'makeup', 'Compact / Powder', 'Portable pressed powder for touch-ups', 'Talc, Mica, Iron Oxides, Vitamin E', 'Convenient, Buildable coverage, Matte finish', ARRAY['all'], 28.00, 200, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('Banana Powder', 'banana-powder', 'makeup', 'Compact / Powder', 'Yellow-toned powder for brightening under-eyes', 'Silica, Mica, Yellow Iron Oxide, Vitamin E', 'Brightens, Sets concealer, Color-corrects', ARRAY['all'], 30.00, 160, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Loose Setting Powder', 'loose-setting-powder', 'makeup', 'Compact / Powder', 'Finely-milled loose powder for flawless finish', 'Silica, Mica, Titanium Dioxide, Vitamin E', 'Smooth finish, Sets makeup, Lightweight', ARRAY['all'], 32.00, 150, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796'),
('HD Powder', 'hd-powder', 'makeup', 'Compact / Powder', 'High-definition powder for camera-ready finish', 'Silica, Mica, Dimethicone, Vitamin E', 'HD finish, No flashback, Professional', ARRAY['all'], 38.00, 130, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'),
('Tinted Powder', 'tinted-powder', 'makeup', 'Compact / Powder', 'Sheer tinted powder with light coverage', 'Mica, Iron Oxides, Titanium Dioxide, Vitamin E', 'Sheer coverage, Natural finish, Buildable', ARRAY['all'], 29.00, 170, 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796');
